// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSaKucBe30ESGQriDkKuKKReq7gL71mII',
    appId: '1:347461208417:web:c1a61523b6ba3fca845d20',
    messagingSenderId: '347461208417',
    projectId: 'notes-9cf51',
    authDomain: 'notes-9cf51.firebaseapp.com',
    storageBucket: 'notes-9cf51.firebasestorage.app',
    measurementId: 'G-XDHPELLLJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGkHydDbWG5J5MZJa52ZAJ1Uzs6uOkZ_Q',
    appId: '1:347461208417:android:dcfb233a54525c0a845d20',
    messagingSenderId: '347461208417',
    projectId: 'notes-9cf51',
    storageBucket: 'notes-9cf51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnBgIG4XHX8U-3EuNcjS1ic6mBnyYUv_8',
    appId: '1:347461208417:ios:f7c2394103cdb404845d20',
    messagingSenderId: '347461208417',
    projectId: 'notes-9cf51',
    storageBucket: 'notes-9cf51.firebasestorage.app',
    iosBundleId: 'com.example.secureNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnBgIG4XHX8U-3EuNcjS1ic6mBnyYUv_8',
    appId: '1:347461208417:ios:f7c2394103cdb404845d20',
    messagingSenderId: '347461208417',
    projectId: 'notes-9cf51',
    storageBucket: 'notes-9cf51.firebasestorage.app',
    iosBundleId: 'com.example.secureNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSaKucBe30ESGQriDkKuKKReq7gL71mII',
    appId: '1:347461208417:web:3e4209b5439c807f845d20',
    messagingSenderId: '347461208417',
    projectId: 'notes-9cf51',
    authDomain: 'notes-9cf51.firebaseapp.com',
    storageBucket: 'notes-9cf51.firebasestorage.app',
    measurementId: 'G-BFNEZMBQEL',
  );
}
